//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets424F4FCEFA5541DB79F4B56781F4D37196A05B1DABE525261EB49DFB1039EFBC))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySets424F4FCEFA5541DB79F4B56781F4D37196A05B1DABE525261EB49DFB1039EFBC : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySets424F4FCEFA5541DB79F4B56781F4D37196A05B1DABE525261EB49DFB1039EFBC()
        {
            this.EdmEntityContainerName = "InnostarModelsContext";
            this.StoreEntityContainerName = "CodeFirstDatabase";
            this.HashOverMappingClosure = "55e631f11d0d2fa76bdc8738b36f1138065fe7c6c53c82f4d8705eab9e48fe37";
            this.HashOverAllExtentViews = "84978dffedb092caf3894911c8d5198fca4b6b69538afd2e2a1b688deb43413a";
            this.ViewCount = 22;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            if ((index == 10))
            {
                return GetView10();
            }
            if ((index == 11))
            {
                return GetView11();
            }
            if ((index == 12))
            {
                return GetView12();
            }
            if ((index == 13))
            {
                return GetView13();
            }
            if ((index == 14))
            {
                return GetView14();
            }
            if ((index == 15))
            {
                return GetView15();
            }
            if ((index == 16))
            {
                return GetView16();
            }
            if ((index == 17))
            {
                return GetView17();
            }
            if ((index == 18))
            {
                return GetView18();
            }
            if ((index == 19))
            {
                return GetView19();
            }
            if ((index == 20))
            {
                return GetView20();
            }
            if ((index == 21))
            {
                return GetView21();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.UserProfile
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.UserProfile", @"
    SELECT VALUE -- Constructing UserProfile
        [CodeFirstDatabaseSchema.UserProfile](T1.UserProfile_Id, T1.UserProfile_UserName, T1.UserProfile_NickName, T1.UserProfile_Email, T1.UserProfile_Phone, T1.UserProfile_ImageId)
    FROM (
        SELECT 
            T.Id AS UserProfile_Id, 
            T.UserName AS UserProfile_UserName, 
            T.NickName AS UserProfile_NickName, 
            T.Email AS UserProfile_Email, 
            T.Phone AS UserProfile_Phone, 
            T.ImageId AS UserProfile_ImageId, 
            True AS _from0
        FROM InnostarModelsContext.UserProfiles AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.DataFile
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.DataFile", @"
    SELECT VALUE -- Constructing DataFile
        [CodeFirstDatabaseSchema.DataFile](T1.DataFile_Id, T1.DataFile_OriginalFileName, T1.DataFile_LocalFileName, T1.DataFile_FileType)
    FROM (
        SELECT 
            T.Id AS DataFile_Id, 
            T.OriginalFileName AS DataFile_OriginalFileName, 
            T.LocalFileName AS DataFile_LocalFileName, 
            T.FileType AS DataFile_FileType, 
            True AS _from0
        FROM InnostarModelsContext.DataFiles AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.ChatUser
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.ChatUser", @"
    SELECT VALUE -- Constructing ChatUser
        [CodeFirstDatabaseSchema.ChatUser](T1.ChatUser_Id, T1.ChatUser_Login, T1.ChatUser_XmppLogin, T1.ChatUser_Name, T1.ChatUser_Email, T1.ChatUser_Phone, T1.ChatUser_PasswordRecoveryType, T1.ChatUser_PasswordRecoveryQuestion, T1.ChatUser_PasswordRecoveryAnswer, T1.ChatUser_SafeModeActivated, T1.ChatUser_Disabled, T1.ChatUser_Uuid, T1.ChatUser_ImageId, T1.ChatUser_PasswordHash, T1.ChatUser_PasswordSalt)
    FROM (
        SELECT 
            T.Id AS ChatUser_Id, 
            T.Login AS ChatUser_Login, 
            T.XmppLogin AS ChatUser_XmppLogin, 
            T.Name AS ChatUser_Name, 
            T.Email AS ChatUser_Email, 
            T.Phone AS ChatUser_Phone, 
            T.PasswordRecoveryType AS ChatUser_PasswordRecoveryType, 
            T.PasswordRecoveryQuestion AS ChatUser_PasswordRecoveryQuestion, 
            T.PasswordRecoveryAnswer AS ChatUser_PasswordRecoveryAnswer, 
            T.SafeModeActivated AS ChatUser_SafeModeActivated, 
            T.Disabled AS ChatUser_Disabled, 
            T.Uuid AS ChatUser_Uuid, 
            T.ImageId AS ChatUser_ImageId, 
            T.PasswordHash AS ChatUser_PasswordHash, 
            T.PasswordSalt AS ChatUser_PasswordSalt, 
            True AS _from0
        FROM InnostarModelsContext.ChatUsers AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.UserToken
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.UserToken", @"
    SELECT VALUE -- Constructing UserToken
        [CodeFirstDatabaseSchema.UserToken](T1.UserToken_Id, T1.UserToken_Token, T1.UserToken_UserId, T1.UserToken_CreatedOn)
    FROM (
        SELECT 
            T.Id AS UserToken_Id, 
            T.Token AS UserToken_Token, 
            T.UserId AS UserToken_UserId, 
            T.CreatedOn AS UserToken_CreatedOn, 
            True AS _from0
        FROM InnostarModelsContext.UserTokens AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.RecoverPasswordRequest
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.RecoverPasswordRequest", @"
    SELECT VALUE -- Constructing RecoverPasswordRequest
        [CodeFirstDatabaseSchema.RecoverPasswordRequest](T1.RecoverPasswordRequest_Id, T1.RecoverPasswordRequest_RequestKey, T1.RecoverPasswordRequest_IsActive, T1.RecoverPasswordRequest_RequestAcceptedTime, T1.RecoverPasswordRequest_UserId)
    FROM (
        SELECT 
            T.Id AS RecoverPasswordRequest_Id, 
            T.RequestKey AS RecoverPasswordRequest_RequestKey, 
            T.IsActive AS RecoverPasswordRequest_IsActive, 
            T.RequestAcceptedTime AS RecoverPasswordRequest_RequestAcceptedTime, 
            T.UserId AS RecoverPasswordRequest_UserId, 
            True AS _from0
        FROM InnostarModelsContext.RecoverPasswordRequests AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for InnostarModelsContext.UserProfiles
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("InnostarModelsContext.UserProfiles", @"
    SELECT VALUE -- Constructing UserProfiles
        [Innostar.Dal.Infrastructure.UserProfile](T1.UserProfile_Id, T1.UserProfile_UserName, T1.UserProfile_NickName, T1.UserProfile_Email, T1.UserProfile_Phone, T1.UserProfile_ImageId)
    FROM (
        SELECT 
            T.Id AS UserProfile_Id, 
            T.UserName AS UserProfile_UserName, 
            T.NickName AS UserProfile_NickName, 
            T.Email AS UserProfile_Email, 
            T.Phone AS UserProfile_Phone, 
            T.ImageId AS UserProfile_ImageId, 
            True AS _from0
        FROM CodeFirstDatabase.UserProfile AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for InnostarModelsContext.DataFiles
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("InnostarModelsContext.DataFiles", @"
    SELECT VALUE -- Constructing DataFiles
        [Innostar.Dal.Infrastructure.DataFile](T1.DataFile_Id, T1.DataFile_OriginalFileName, T1.DataFile_LocalFileName, T1.DataFile_FileType)
    FROM (
        SELECT 
            T.Id AS DataFile_Id, 
            T.OriginalFileName AS DataFile_OriginalFileName, 
            T.LocalFileName AS DataFile_LocalFileName, 
            T.FileType AS DataFile_FileType, 
            True AS _from0
        FROM CodeFirstDatabase.DataFile AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for InnostarModelsContext.ChatUsers
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("InnostarModelsContext.ChatUsers", @"
    SELECT VALUE -- Constructing ChatUsers
        [Innostar.Dal.Infrastructure.ChatUser](T1.ChatUser_Id, T1.ChatUser_Login, T1.ChatUser_XmppLogin, T1.ChatUser_Name, T1.ChatUser_Email, T1.ChatUser_Phone, T1.ChatUser_PasswordRecoveryType, T1.ChatUser_PasswordRecoveryQuestion, T1.ChatUser_PasswordRecoveryAnswer, T1.ChatUser_SafeModeActivated, T1.ChatUser_Disabled, T1.ChatUser_Uuid, T1.ChatUser_ImageId, T1.ChatUser_PasswordHash, T1.ChatUser_PasswordSalt)
    FROM (
        SELECT 
            T.Id AS ChatUser_Id, 
            T.Login AS ChatUser_Login, 
            T.XmppLogin AS ChatUser_XmppLogin, 
            T.Name AS ChatUser_Name, 
            T.Email AS ChatUser_Email, 
            T.Phone AS ChatUser_Phone, 
            T.PasswordRecoveryType AS ChatUser_PasswordRecoveryType, 
            T.PasswordRecoveryQuestion AS ChatUser_PasswordRecoveryQuestion, 
            T.PasswordRecoveryAnswer AS ChatUser_PasswordRecoveryAnswer, 
            T.SafeModeActivated AS ChatUser_SafeModeActivated, 
            T.Disabled AS ChatUser_Disabled, 
            T.Uuid AS ChatUser_Uuid, 
            T.ImageId AS ChatUser_ImageId, 
            T.PasswordHash AS ChatUser_PasswordHash, 
            T.PasswordSalt AS ChatUser_PasswordSalt, 
            True AS _from0
        FROM CodeFirstDatabase.ChatUser AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for InnostarModelsContext.UserTokens
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("InnostarModelsContext.UserTokens", @"
    SELECT VALUE -- Constructing UserTokens
        [Innostar.Dal.Infrastructure.UserToken](T1.UserToken_Id, T1.UserToken_Token, T1.UserToken_UserId, T1.UserToken_CreatedOn)
    FROM (
        SELECT 
            T.Id AS UserToken_Id, 
            T.Token AS UserToken_Token, 
            T.UserId AS UserToken_UserId, 
            T.CreatedOn AS UserToken_CreatedOn, 
            True AS _from0
        FROM CodeFirstDatabase.UserToken AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for InnostarModelsContext.RecoverPasswordRequests
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("InnostarModelsContext.RecoverPasswordRequests", @"
    SELECT VALUE -- Constructing RecoverPasswordRequests
        [Innostar.Dal.Infrastructure.RecoverPasswordRequest](T1.RecoverPasswordRequest_Id, T1.RecoverPasswordRequest_RequestKey, T1.RecoverPasswordRequest_IsActive, T1.RecoverPasswordRequest_RequestAcceptedTime, T1.RecoverPasswordRequest_UserId)
    FROM (
        SELECT 
            T.Id AS RecoverPasswordRequest_Id, 
            T.RequestKey AS RecoverPasswordRequest_RequestKey, 
            T.IsActive AS RecoverPasswordRequest_IsActive, 
            T.RequestAcceptedTime AS RecoverPasswordRequest_RequestAcceptedTime, 
            T.UserId AS RecoverPasswordRequest_UserId, 
            True AS _from0
        FROM CodeFirstDatabase.RecoverPasswordRequest AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.RoomKey
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView10()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.RoomKey", @"
    SELECT VALUE -- Constructing RoomKey
        [CodeFirstDatabaseSchema.RoomKey](T1.RoomKey_Id, T1.RoomKey_RoomId, T1.RoomKey_RoomPasswordKey, T1.RoomKey_StartTime, T1.RoomKey_EndTime)
    FROM (
        SELECT 
            T.Id AS RoomKey_Id, 
            T.RoomId AS RoomKey_RoomId, 
            T.RoomPasswordKey AS RoomKey_RoomPasswordKey, 
            T.StartTime AS RoomKey_StartTime, 
            T.EndTime AS RoomKey_EndTime, 
            True AS _from0
        FROM InnostarModelsContext.RoomKeys AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for InnostarModelsContext.RoomKeys
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView11()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("InnostarModelsContext.RoomKeys", @"
    SELECT VALUE -- Constructing RoomKeys
        [Innostar.Dal.Infrastructure.RoomKey](T1.RoomKey_Id, T1.RoomKey_RoomId, T1.RoomKey_RoomPasswordKey, T1.RoomKey_StartTime, T1.RoomKey_EndTime)
    FROM (
        SELECT 
            T.Id AS RoomKey_Id, 
            T.RoomId AS RoomKey_RoomId, 
            T.RoomPasswordKey AS RoomKey_RoomPasswordKey, 
            T.StartTime AS RoomKey_StartTime, 
            T.EndTime AS RoomKey_EndTime, 
            True AS _from0
        FROM CodeFirstDatabase.RoomKey AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.Membership
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView12()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.Membership", @"
    SELECT VALUE -- Constructing Membership
        [CodeFirstDatabaseSchema.Membership](T1.Membership_UserId, T1.Membership_ConfirmationToken, T1.Membership_CreateDate, T1.Membership_IsConfirmed, T1.Membership_LastPasswordFailureDate, T1.Membership_Password, T1.Membership_PasswordChangedDate, T1.Membership_PasswordFailuresSinceLastSuccess, T1.Membership_PasswordSalt, T1.Membership_PasswordVerificationToken, T1.Membership_PasswordVerificationTokenExpirationDate)
    FROM (
        SELECT 
            T.Id AS Membership_UserId, 
            T.ConfirmationToken AS Membership_ConfirmationToken, 
            T.CreateDate AS Membership_CreateDate, 
            T.IsConfirmed AS Membership_IsConfirmed, 
            T.LastPasswordFailureDate AS Membership_LastPasswordFailureDate, 
            T.Password AS Membership_Password, 
            T.PasswordChangedDate AS Membership_PasswordChangedDate, 
            T.PasswordFailuresSinceLastSuccess AS Membership_PasswordFailuresSinceLastSuccess, 
            T.PasswordSalt AS Membership_PasswordSalt, 
            T.PasswordVerificationToken AS Membership_PasswordVerificationToken, 
            T.PasswordVerificationTokenExpirationDate AS Membership_PasswordVerificationTokenExpirationDate, 
            True AS _from0
        FROM InnostarModelsContext.Memberships AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.OAuthMembership
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView13()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.OAuthMembership", @"
    SELECT VALUE -- Constructing OAuthMembership
        [CodeFirstDatabaseSchema.OAuthMembership](T1.OAuthMembership_Provider, T1.OAuthMembership_ProviderUserId, T1.OAuthMembership_UserId)
    FROM (
        SELECT 
            T.Provider AS OAuthMembership_Provider, 
            T.ProviderUserId AS OAuthMembership_ProviderUserId, 
            T.UserId AS OAuthMembership_UserId, 
            True AS _from0
        FROM InnostarModelsContext.OAuthMemberships AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.Role
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView14()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.Role", @"
    SELECT VALUE -- Constructing Role
        [CodeFirstDatabaseSchema.Role](T1.Role_RoleId, T1.Role_RoleDisplayName, T1.Role_RoleName)
    FROM (
        SELECT 
            T.Id AS Role_RoleId, 
            T.RoleDisplayName AS Role_RoleDisplayName, 
            T.RoleName AS Role_RoleName, 
            True AS _from0
        FROM InnostarModelsContext.Roles AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.User
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView15()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.User", @"
    SELECT VALUE -- Constructing User
        [CodeFirstDatabaseSchema.User](T1.User_UserId, T1.User_Email, T1.User_UserName)
    FROM (
        SELECT 
            T.Id AS User_UserId, 
            T.Email AS User_Email, 
            T.UserName AS User_UserName, 
            True AS _from0
        FROM InnostarModelsContext.Users AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.MembershipRole
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView16()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.MembershipRole", @"
    SELECT VALUE -- Constructing MembershipRole
        [CodeFirstDatabaseSchema.MembershipRole](T1.MembershipRole_UserId, T1.MembershipRole_RoleId)
    FROM (
        SELECT 
            Key(T.Membership_Roles_Source).Id AS MembershipRole_UserId, 
            Key(T.Membership_Roles_Target).Id AS MembershipRole_RoleId, 
            True AS _from0
        FROM InnostarModelsContext.Membership_Roles AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for InnostarModelsContext.Memberships
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView17()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("InnostarModelsContext.Memberships", @"
    SELECT VALUE -- Constructing Memberships
        [Innostar.Dal.Infrastructure.Membership](T1.Membership_Id, T1.Membership_ConfirmationToken, T1.Membership_CreateDate, T1.Membership_IsConfirmed, T1.Membership_LastPasswordFailureDate, T1.Membership_Password, T1.Membership_PasswordChangedDate, T1.Membership_PasswordFailuresSinceLastSuccess, T1.Membership_PasswordSalt, T1.Membership_PasswordVerificationToken, T1.Membership_PasswordVerificationTokenExpirationDate)
    FROM (
        SELECT 
            T.UserId AS Membership_Id, 
            T.ConfirmationToken AS Membership_ConfirmationToken, 
            T.CreateDate AS Membership_CreateDate, 
            T.IsConfirmed AS Membership_IsConfirmed, 
            T.LastPasswordFailureDate AS Membership_LastPasswordFailureDate, 
            T.Password AS Membership_Password, 
            T.PasswordChangedDate AS Membership_PasswordChangedDate, 
            T.PasswordFailuresSinceLastSuccess AS Membership_PasswordFailuresSinceLastSuccess, 
            T.PasswordSalt AS Membership_PasswordSalt, 
            T.PasswordVerificationToken AS Membership_PasswordVerificationToken, 
            T.PasswordVerificationTokenExpirationDate AS Membership_PasswordVerificationTokenExpirationDate, 
            True AS _from0
        FROM CodeFirstDatabase.Membership AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for InnostarModelsContext.OAuthMemberships
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView18()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("InnostarModelsContext.OAuthMemberships", @"
    SELECT VALUE -- Constructing OAuthMemberships
        [Innostar.Dal.Infrastructure.OAuthMembership](T1.OAuthMembership_Provider, T1.OAuthMembership_ProviderUserId, T1.OAuthMembership_UserId)
    FROM (
        SELECT 
            T.Provider AS OAuthMembership_Provider, 
            T.ProviderUserId AS OAuthMembership_ProviderUserId, 
            T.UserId AS OAuthMembership_UserId, 
            True AS _from0
        FROM CodeFirstDatabase.OAuthMembership AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for InnostarModelsContext.Roles
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView19()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("InnostarModelsContext.Roles", @"
    SELECT VALUE -- Constructing Roles
        [Innostar.Dal.Infrastructure.Role](T1.Role_Id, T1.Role_RoleDisplayName, T1.Role_RoleName)
    FROM (
        SELECT 
            T.RoleId AS Role_Id, 
            T.RoleDisplayName AS Role_RoleDisplayName, 
            T.RoleName AS Role_RoleName, 
            True AS _from0
        FROM CodeFirstDatabase.Role AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for InnostarModelsContext.Users
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView20()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("InnostarModelsContext.Users", @"
    SELECT VALUE -- Constructing Users
        [Innostar.Dal.Infrastructure.User](T1.User_Id, T1.User_Email, T1.User_UserName)
    FROM (
        SELECT 
            T.UserId AS User_Id, 
            T.Email AS User_Email, 
            T.UserName AS User_UserName, 
            True AS _from0
        FROM CodeFirstDatabase.User AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for InnostarModelsContext.Membership_Roles
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView21()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("InnostarModelsContext.Membership_Roles", @"
    SELECT VALUE -- Constructing Membership_Roles
        [Innostar.Dal.Infrastructure.Membership_Roles](T3.[Membership_Roles.Membership_Roles_Source], T3.[Membership_Roles.Membership_Roles_Target])
    FROM (
        SELECT -- Constructing Membership_Roles_Source
            CreateRef(InnostarModelsContext.Memberships, row(T2.[Membership_Roles.Membership_Roles_Source.Id]), [Innostar.Dal.Infrastructure.Membership]) AS [Membership_Roles.Membership_Roles_Source], 
            T2.[Membership_Roles.Membership_Roles_Target]
        FROM (
            SELECT -- Constructing Membership_Roles_Target
                T1.[Membership_Roles.Membership_Roles_Source.Id], 
                CreateRef(InnostarModelsContext.Roles, row(T1.[Membership_Roles.Membership_Roles_Target.Id]), [Innostar.Dal.Infrastructure.Role]) AS [Membership_Roles.Membership_Roles_Target]
            FROM (
                SELECT 
                    T.UserId AS [Membership_Roles.Membership_Roles_Source.Id], 
                    T.RoleId AS [Membership_Roles.Membership_Roles_Target.Id], 
                    True AS _from0
                FROM CodeFirstDatabase.MembershipRole AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }
    }
}

