//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innostar.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InnostarStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InnostarStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Innostar.UI.InnostarStrings", typeof(InnostarStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направления деятельности.
        /// </summary>
        public static string ActivityDirections {
            get {
                return ResourceManager.GetString("ActivityDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типы деятельности.
        /// </summary>
        public static string ActivityTypes {
            get {
                return ResourceManager.GetString("ActivityTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интенсивность активности.
        /// </summary>
        public static string ActivityValue {
            get {
                return ResourceManager.GetString("ActivityValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес организации.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аннотация.
        /// </summary>
        public static string Annotation {
            get {
                return ResourceManager.GetString("Annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связанная организация.
        /// </summary>
        public static string DependentOrganization {
            get {
                return ResourceManager.GetString("DependentOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образовательное учреждение.
        /// </summary>
        public static string EducationalInstitution {
            get {
                return ResourceManager.GetString("EducationalInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидный email.
        /// </summary>
        public static string Email_Val_Message {
            get {
                return ResourceManager.GetString("Email_Val_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время окончания.
        /// </summary>
        public static string ExpirationTime {
            get {
                return ResourceManager.GetString("ExpirationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на профиль в  Facebook.
        /// </summary>
        public static string FacebookProfile {
            get {
                return ResourceManager.GetString("FacebookProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешил публиковать e-mail .
        /// </summary>
        public static string IsEmailPublic {
            get {
                return ResourceManager.GetString("IsEmailPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешил публиковать телефон.
        /// </summary>
        public static string IsPhonePublic {
            get {
                return ResourceManager.GetString("IsPhonePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата последнего обновления.
        /// </summary>
        public static string LastUpdateTime {
            get {
                return ResourceManager.GetString("LastUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Широта.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на профиль в LinkedIn .
        /// </summary>
        public static string LinkedInProfile {
            get {
                return ResourceManager.GetString("LinkedInProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Долгота.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка валидации сохраняемых данных. Данные некорректны..
        /// </summary>
        public static string Model_Val_Message {
            get {
                return ResourceManager.GetString("Model_Val_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма организации.
        /// </summary>
        public static string OrganizationForm {
            get {
                return ResourceManager.GetString("OrganizationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организация.
        /// </summary>
        public static string OrganizationTitle {
            get {
                return ResourceManager.GetString("OrganizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статусы пользователя.
        /// </summary>
        public static string PersonStatuses {
            get {
                return ResourceManager.GetString("PersonStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Персона.
        /// </summary>
        public static string PersonTitle {
            get {
                return ResourceManager.GetString("PersonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Практическая важность.
        /// </summary>
        public static string PracticalImportance {
            get {
                return ResourceManager.GetString("PracticalImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус проекта.
        /// </summary>
        public static string ProjectStateId {
            get {
                return ResourceManager.GetString("ProjectStateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проект.
        /// </summary>
        public static string ProjectTitle {
            get {
                return ResourceManager.GetString("ProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата регистрации.
        /// </summary>
        public static string RegistrationTime {
            get {
                return ResourceManager.GetString("RegistrationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип взаимосвязи.
        /// </summary>
        public static string RelationType {
            get {
                return ResourceManager.GetString("RelationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение не может быть пустым.
        /// </summary>
        public static string Required_Val_Message {
            get {
                return ResourceManager.GetString("Required_Val_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус ресурса.
        /// </summary>
        public static string ResourceStateId {
            get {
                return ResourceManager.GetString("ResourceStateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип ресурса.
        /// </summary>
        public static string ResourceTypeId {
            get {
                return ResourceManager.GetString("ResourceTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое описание.
        /// </summary>
        public static string ShortSpecification {
            get {
                return ResourceManager.GetString("ShortSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Specification {
            get {
                return ResourceManager.GetString("Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введенное значение слишком длинное.
        /// </summary>
        public static string String_Length_Val_Message {
            get {
                return ResourceManager.GetString("String_Length_Val_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теги.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на профиль в Twitter .
        /// </summary>
        public static string TwitterProfile {
            get {
                return ResourceManager.GetString("TwitterProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на профиль в Вконтакте .
        /// </summary>
        public static string VkProfile {
            get {
                return ResourceManager.GetString("VkProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Веб-сайт .
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
